Repository FE14-Part4-Team2/coworkers, pull requests merged in 2025-06, with the labels that each got.

#61 ✨ feat: 팀 페이지 할일목록 배지 구현
  public/icons/icon-badge.svg
  src/app/dashboard/page.tsx
  src/components/feature/Dashboard/ListGroup/ListBadge.tsx
Labels: ✨ Feature

#57 ✨ feat: 카드 컴포넌트 및 모집게시판 레이아웃 구현
  eslint.config.mjs
  public/icons/icon-bookmarks.svg
  public/icons/icon-search-gray.svg
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/reset-password/layout.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/user-setting/layout.tsx
  src/app/(board)/boards/layout.tsx
  src/app/(board)/boards/new/layout.tsx
  src/app/(board)/boards/page.tsx
  src/app/(team)/create/layout.tsx
  src/app/(team)/edit/layout.tsx
  src/app/(team)/join/layout.tsx
  src/app/(team)/select/layout.tsx
  src/app/dashboard/layout.tsx
  src/app/layout.tsx
  src/app/myhistory/layout.tsx
  src/components/feature/Boards/BoardBestList.tsx
  src/components/feature/Boards/BoardList.tsx
  src/components/feature/Boards/LongCard.tsx
  src/components/feature/Boards/SearchInput.tsx
  src/components/feature/Boards/ShortCard.tsx
  src/layouts/Header/AuthHeader.tsx
  src/layouts/Header/Header.tsx
  src/layouts/Header/LandingHeader.tsx
  src/layouts/Header/TeamDropdown.tsx
  src/layouts/Header/UserDropdown.tsx
  tailwind.config.ts
Labels: ✨ Feature

#70 ✨ feat: 비밀번호 재설정 페이지 UI 구현
  src/app/(auth)/reset-password/page.tsx
Labels: ✨ Feature, 🎨 Style

#74 ✨feat: 로그인 페이지 UI 구현
  public/icons/icon-kakao.svg
  src/app/(auth)/login/page.tsx
  src/components/feature/Auth/DividerWithText.tsx
  src/components/feature/Auth/KakaoLogin.tsx
  src/components/feature/Auth/LoginForm/LoginForm.tsx
  src/components/feature/Auth/LoginForm/SendEmailModal.tsx
Labels: ✨ Feature, 🎨 Style

#72 ✨ feat: GitHub Actions를 이용한 EC2 자동 배포 설정 추가
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#78 ✨ feat: 게시글 작성 페이지 UI 구현
  package.json
  pnpm-lock.yaml
  public/icons/icon-plus-gray.svg
  src/app/(board)/boards/new/layout.tsx
  src/app/(board)/boards/new/page.tsx
  src/app/(board)/boards/page.tsx
  src/components/common/Input/Input.tsx
  src/components/common/TextArea/TextArea.tsx
  src/components/feature/Boards/Card/LongCard.tsx
  src/components/feature/Boards/Card/ShortCard.tsx
  src/components/feature/Boards/List/BoardBestList.tsx
  src/components/feature/Boards/List/BoardList.tsx
  src/components/feature/Boards/List/FilterDropdown.tsx
  src/components/feature/Boards/List/SearchInput.tsx
  src/components/feature/Boards/New/BoardsForm.tsx
  src/components/feature/Boards/New/ImageUploader.tsx
  src/components/feature/Boards/New/LabeledField.tsx
  src/layouts/Header/Header.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Style

#87 🐛 fix: proxy 서버 핸들러 함수 export 제거
  src/app/api/proxy/[...path]/route.ts
Labels: 🌏 Deploy, 🐞 BugFix, 📬 API

#88 ✨ feat: 비밀번호 재설정 페이지 기능 추가
  public/icons/icon-info.svg
  public/icons/icon-toast-check.svg
  src/app/(auth)/reset-password/page.tsx
  src/app/layout.tsx
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/ToastPortal.tsx
  src/stores/toastStore.ts
Labels: ✨ Feature

#91 ✨ feat: 게시글 상세 페이지 UI 구현
  public/icons/icon-vector.svg
  src/app/(board)/boards/[id]/edit/page.tsx
  src/app/(board)/boards/[id]/layout.tsx
  src/app/(board)/boards/[teamId]/ArticleMock.ts
  src/app/(board)/boards/[teamId]/CommentMock.ts
  src/app/(board)/boards/[teamId]/[articleId]/page.tsx
  src/app/(board)/boards/[teamId]/edit/layout.tsx
  src/app/(board)/boards/[teamId]/edit/page.tsx
  src/app/(board)/boards/[teamId]/layout.tsx
  src/app/(board)/boards/[teamId]/new/page.tsx
  src/app/(board)/boards/[teamId]/page.tsx
  src/components/common/Dropdown/Trigger.tsx
  src/components/common/TextArea/TextArea.tsx
  src/components/feature/Boards/Article/ArticleDetail.tsx
  src/components/feature/Boards/Card/LongCard.tsx
  src/components/feature/Boards/Card/ShortCard.tsx
  src/components/feature/Boards/Comment/CommentDropdown.tsx
  src/components/feature/Boards/Comment/CommentForm.tsx
  src/components/feature/Boards/Comment/CommentList.tsx
  src/components/feature/Boards/List/BoardBestList.tsx
  src/components/feature/Boards/List/BoardList.tsx
  src/layouts/Header/TeamDropdown.tsx
  src/types/article.ts
  tailwind.config.ts
Labels: ✨ Feature

#84 ✨ feat: 할일 리스트 페이지 - 리스트 상세 UI
  src/app/(workspace)/[teamId]/(task-lists)/task-lists/[listId]/page.tsx
  src/app/(workspace)/[teamId]/page.tsx
  src/app/(workspace)/mock.ts
  src/components/feature/TaskList/TaskItem.tsx
Labels: ✨ Feature, 🎨 Style

#96 ✨ feat: 팀 페이지 리포트 그룹 구현
  src/app/(workspace)/[teamId]/page.tsx
  src/app/(workspace)/mock.ts
  src/components/feature/Dashboard/ReportGroup/ReportBox.tsx
  src/components/feature/Dashboard/ReportGroup/ReportChart.tsx
Labels: ✨ Feature

#93 ✨ feat: 로그인 기능 구현
  src/api/auth/auth.query.ts
  src/api/user/user.query.ts
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/user-setting/layout.tsx
  src/app/layout.tsx
  src/components/feature/Auth/AuthProvider/AuthProvider.tsx
  src/components/feature/Auth/LoginForm/LoginForm.tsx
  src/components/feature/Auth/LoginForm/SendEmailModal.tsx
  src/stores/authStore.ts
Labels: ✨ Feature

#94 ✨ feat: 회원가입 기능 구현
  src/app/(auth)/sign-up/page.tsx
  src/components/feature/Auth/SignupForm/SignupForm.tsx
Labels: ✨ Feature

#104 ✨ feat: 카카오 로그인/회원가입 구현
  package-lock.json
  package.json
  src/api/auth/auth.query.ts
  src/api/auth/auth.schema.ts
  src/api/auth/auth.service.ts
  src/app/(auth)/oauth/kakao/layout.tsx
  src/app/(auth)/oauth/kakao/page.tsx
  src/app/api/auth/kakao/route.ts
  src/components/feature/Auth/KakaoLogin.tsx
  src/components/feature/Auth/SignupForm/SignupForm.tsx
Labels: ✨ Feature

#106 ✨ feat: 팀 페이지 멤버 그룹 구현
  public/icons/icon-delete-people.svg
  src/app/(workspace)/[teamId]/page.tsx
  src/app/(workspace)/mock.ts
  src/components/feature/Dashboard/MemberGroup/MemberBox.tsx
  src/components/feature/Dashboard/ReportGroup/ReportChart.tsx
Labels: ✨ Feature

#112 ✨ feat: 팀 참여 페이지 UI 구현
  src/app/(team)/create/page.tsx
  src/app/(team)/join/page.tsx
  src/components/team/TeamFormLayout.tsx
Labels: ✨ Feature

#118 ✨ feat: 게시글 상세보기, 좋아요, 댓글 API 연동
  pnpm-lock.yaml
  public/icons/icon-heart-filled.svg
  src/api/article-comment/article-comment.query.ts
  src/api/article/article.query.ts
  src/api/article/article.service.ts
  src/app/(board)/boards/[articleId]/page.tsx
  src/app/(board)/boards/[teamId]/ArticleMock.ts
  src/app/(board)/boards/[teamId]/CommentMock.ts
  src/app/(board)/boards/[teamId]/[articleId]/page.tsx
  src/app/(board)/boards/[teamId]/edit/layout.tsx
  src/app/(board)/boards/[teamId]/edit/page.tsx
  src/components/feature/Boards/Article/ArticleDetail.tsx
  src/components/feature/Boards/Article/LikeButton.tsx
  src/components/feature/Boards/Card/LongCard.tsx
  src/components/feature/Boards/Card/ShortCard.tsx
  src/components/feature/Boards/Comment/CommentDropdown.tsx
  src/components/feature/Boards/Comment/CommentForm.tsx
  src/components/feature/Boards/Comment/CommentItem.tsx
  src/components/feature/Boards/Comment/CommentList.tsx
  src/styles/sharedCardStyles.ts
  src/types/article.ts
Labels: ✨ Feature

#122 ✨ feat: 마이 히스토리 페이지 UI 구현
  src/app/myhistory/historyMock.ts
  src/app/myhistory/page.tsx
Labels: ✨ Feature

#127 ✨ feat: 팀 선택 페이지 UI 구현
  src/app/(team)/select/page.tsx
Labels: ✨ Feature

#132 ✨ feat: 게시글 수정 삭제 API 연동
  src/api/article/article.query.ts
  src/api/article/article.service.ts
  src/app/(board)/boards/[articleId]/edit/page.tsx
  src/app/(board)/boards/[articleId]/page.tsx
  src/app/(board)/boards/new/page.tsx
  src/components/feature/Boards/Article/ArticleDetail.tsx
  src/components/feature/Boards/Comment/CommentDropdown.tsx
  src/components/feature/Boards/Comment/CommentItem.tsx
  src/components/feature/Boards/Comment/CommentList.tsx
  src/components/feature/Boards/Edit/EditForm.tsx
  src/components/feature/Boards/New/BoardsForm.tsx
  src/components/feature/Boards/New/ImageUploader.tsx
  src/hooks/useArticleComments.ts
  src/hooks/useImageUploadHandler.ts
  src/hooks/useImageUploader.ts
  src/layouts/Header/Header.tsx
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#138 ✨ feat: 팀 생성 페이지 기능 구현 및 API 연동
  src/app/(team)/create/page.tsx
  src/app/(workspace)/[teamId]/edit/page.tsx
  src/components/feature/Team/ProfileImageUploader.tsx
  src/components/feature/Team/ProfileUploader.tsx
  src/components/feature/Team/TeamFormLayout.tsx
  src/components/feature/Team/TeamNameError.tsx
  src/constants/team.ts
  src/stores/ useTeamStore.ts
Labels: ✨ Feature

#140 ✨ feat: 팀 선택 페이지 기능 구현
  src/app/(team)/select/page.tsx
Labels: ✨ Feature

#146 ✨ feat: 게시글 확인 모달 및 토스트 알림 추가
  src/app/(board)/boards/[articleId]/edit/page.tsx
  src/app/(board)/boards/[articleId]/page.tsx
  src/app/(board)/boards/new/page.tsx
  src/components/common/Modal/DeleteModal.tsx
  src/components/feature/Boards/Article/ArticleDetail.tsx
  src/components/feature/Boards/Comment/CommentDropdown.tsx
  src/components/feature/Boards/Comment/CommentForm.tsx
  src/components/feature/Boards/Comment/CommentItem.tsx
  src/components/feature/Boards/Comment/CommentList.tsx
  src/layouts/Header/Header.tsx
  src/stores/modalStore.ts
Labels: ✨ Feature

#143 ✨ feat: 랜딩 페이지 구현
  public/images/landing/landing-feature-bg.png
  public/images/landing/landing-feature-bg02.png
  public/images/landing/landing-floating.png
  public/images/landing/landing-modal.png
  public/images/landing/landing-top-lg.png
  public/images/landing/landing-top-md.png
  public/images/landing/landing-top-sm.png
  src/app/page.tsx
  src/components/feature/Landing/FeatureSection.tsx
  src/components/feature/Landing/InteractiveGridBg.tsx
  src/hooks/useMediaQuery.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Style

#147 ✨ feat: 멤버 모달 기능 추가 및 토스트 색상 적용
  src/app/(workspace)/[teamId]/page.tsx
  src/app/invite/page.tsx
  src/components/common/Modal/ProfileModal.tsx
  src/components/feature/Dashboard/MemberGroup/MemberBox.tsx
  src/components/feature/Dashboard/TeamBar/TeamBarDropdown.tsx
Labels: ✨ Feature

#156 ✨ feat: 마이 히스토리 페이지 기능 구현 및 API 연동
  src/app/myhistory/page.tsx
Labels: ✨ Feature

#163 ✨ feat: 팀 참여 페이지 기능 구현 및 API 연동
  src/app/(team)/join/page.tsx
  src/components/feature/Team/TeamFormLayout.tsx
  src/constants/team.ts
Labels: ✨ Feature

#160 🐛 fix: 모달 버튼 컴포넌트 적용 및 색상 수정
  src/app/(workspace)/[teamId]/page.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/PasswordChangeModal.tsx
  src/components/common/Modal/ProfileModal.tsx
  src/components/common/Modal/TodoCreateModal.tsx
  src/components/common/Modal/TodoEditModal.tsx
  src/components/common/Modal/TodoModal.tsx
Labels: ✨ Feature, 🐞 BugFix

#166 ✨ feat: 스켈레톤 UI 구현
  src/app/(workspace)/[teamId]/page.tsx
  src/components/common/Skeleton/Skeleton.tsx
Labels: ✨ Feature

#161 ✨ feat: 게시글 등록시 토큰 추가 및 참여하기 버튼 구현
  src/app/(board)/boards/[articleId]/edit/page.tsx
  src/app/(board)/boards/new/page.tsx
  src/components/common/Modal/NoTokenModal.tsx
  src/components/feature/Boards/Article/ArticleDetail.tsx
  src/components/feature/Boards/Article/JoinButton.tsx
  src/components/feature/Boards/Card/LongCard.tsx
  src/components/feature/Boards/Card/ShortCard.tsx
  src/components/feature/Boards/List/BoardBestList.tsx
  src/components/feature/Boards/List/SearchInput.tsx
  src/components/feature/Boards/New/BoardsForm.tsx
  src/components/feature/Boards/New/LabeledField.tsx
  src/stores/modalStore.ts
  src/styles/sharedCardStyles.ts
Labels: ✨ Feature

#169 ✨ feat: 404 페이지 구현
  src/app/not-found.tsx
Labels: ✨ Feature, 🎨 Style

#189 🐛 fix: 드롭다운 디자인 수정 및 로그아웃 모달 연결
  src/layouts/Header/TeamDropdown.tsx
  src/layouts/Header/TeamListItem.tsx
  src/layouts/Header/UserDropdown.tsx
Labels: ✨ Feature, 🎨 Style, 🐞 BugFix

#188 🐛 fix: 랜딩 페이지 반응형 및 애니메이션 버그 수정
  src/components/feature/Landing/FeatureSection.tsx
Labels: 🐞 BugFix

#180 🐛 fix: auth 관련 페이지 버그 수정
  src/api/fetcher.ts
  src/app/(auth)/oauth/kakao/page.tsx
  src/app/(auth)/reset-password/layout.tsx
  src/app/(auth)/reset-password/page.tsx
  src/components/common/Modal/PasswordChangeModal.tsx
  src/components/feature/Auth/KakaoLogin.tsx
  src/components/feature/Auth/LoginForm/LoginForm.tsx
  src/components/feature/Auth/SettingForm/ProfileImageUploader.tsx
  src/components/feature/Auth/SettingForm/SettingForm.tsx
  src/components/feature/Auth/SignupForm/SignupForm.tsx
Labels: 🐞 BugFix

#186 🐛 fix: 모집글 생성, 수정 통합 버그 수정
  src/api/article/article.query.ts
  src/api/article/article.schema.ts
  src/app/(board)/boards/[articleId]/edit/page.tsx
  src/app/(board)/boards/new/page.tsx
  src/components/feature/Boards/New/BoardsForm.tsx
  src/components/feature/Boards/New/ImageUploader.tsx
  src/hooks/useImageUploadHandler.ts
Labels: 🐞 BugFix

#194 🐛 fix: 카카오 로그인 api 에러 처리 수정
  src/app/api/auth/kakao/route.ts
Labels: 🌏 Deploy, 📬 API

#197 🐛 fix: 드롭다운 랜딩페이지에서 이동할 때 안닫히는 버그 수정
  src/assets/index.ts
  src/components/index.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/layouts/Header/TeamDropdown.tsx
  src/layouts/Header/UserDropdown.tsx
  src/lib/index.ts
  src/stores/index.ts
  src/styles/index.ts
  src/types/index.ts
  src/utils/index.ts
Labels: 🐞 BugFix

#202 🐛 fix: 상세페이지 로그인 분기 처리 및 디자인 수정
  src/app/(board)/boards/[articleId]/page.tsx
  src/components/common/Modal/NoAuthModal.tsx
  src/components/feature/Boards/Article/ArticleDetail.tsx
  src/components/feature/Boards/Article/JoinButton.tsx
  src/components/feature/Boards/Article/LikeButton.tsx
  src/components/feature/Boards/Comment/CommentForm.tsx
  src/components/feature/Boards/Comment/CommentItem.tsx
  src/components/feature/Boards/Comment/CommentList.tsx
  src/stores/modalStore.ts
Labels: ✨ Feature, 🐞 BugFix

#200 🐛 fix: 초대 링크 복사 후 모달 및 중복 목록 처리 추가
  src/app/(workspace)/[teamId]/page.tsx
  src/components/common/Modal/SuccessInviteModal.tsx
  src/stores/modalStore.ts
Labels: ✨ Feature, 🐞 BugFix

#214 ♻️ refactor: input 스타일 정리
  package.json
  pnpm-lock.yaml
  src/components/common/Input/Input.tsx
  src/utils/cn.ts
Labels: 🔨 Refactor

#226 🐛 fix: 로그아웃 시 이동 안되는 버그 수정
  src/layouts/Header/Header.tsx
  src/layouts/Header/UserDropdown.tsx
Labels: 🐞 BugFix

#232 ✨ feat: favicon 설정 및 metadata 설정
  public/favicon.png
  public/metadata.png
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/oauth/kakao/layout.tsx
  src/app/(auth)/reset-password/layout.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/user-setting/layout.tsx
  src/app/(board)/boards/layout.tsx
  src/app/(team)/create/layout.tsx
  src/app/(team)/join/layout.tsx
  src/app/(team)/layout.tsx
  src/app/(team)/select/layout.tsx
  src/app/(workspace)/[teamId]/(task-lists)/task-lists/[listId]/layout.tsx
  src/app/(workspace)/[teamId]/edit/layout.tsx
  src/app/(workspace)/[teamId]/layout.tsx
  src/app/favicon.ico
  src/app/invite/layout.tsx
  src/app/layout.tsx
  src/app/myhistory/layout.tsx
Labels: ✨ Feature

#238 🐛 fix: 마이 히스토리 페이지 텍스트 스타일 수정 및 카카오 환경 변수 수정
  src/app/myhistory/page.tsx
Labels: 🌏 Deploy, 🐞 BugFix
