Repository FE14-Part4-Team2/coworkers, pull requests merged in 2025-05, with the labels that each got.

#12 🔧 chore: 폰트 설치 및 tailwind 테마 설정
  .husky/pre-commit
  eslint.config.mjs
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/layout.tsx
  src/assets/fonts/PretendardVariable.woff2
  src/styles/index.ts
  tailwind.config.ts
Labels: ⚙ Setting

#24 ✨ feat: 공통 Dropdown 컴포넌트 구현
  .github/workflows/auto-reviewer.yml
  package-lock.json
  package.json
  src/app/(board)/boards/page.tsx
  src/components/common/dropdown/filterdropdown.tsx
  src/components/common/dropdown/genericdropdown.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/dropdown/item.tsx
  src/components/common/dropdown/menu.tsx
  src/components/common/dropdown/repeatdropdown.tsx
  src/components/common/dropdown/trigger.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useClickOutside.ts
  src/hooks/usegenericdropdown.tsx
Labels: ✨ Feature, 🎨 Style

#29 :sparkles: feat: 공통 Input 컴포넌트 구현
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/(auth)/login/page.tsx
  src/assets/icons/icon-visibility_off.svg
  src/assets/icons/icon-visibility_on.svg
  src/components/common/Input/ErrorMsg.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Input/PasswordToggle.tsx
Labels: ✨ Feature, 🎨 Style

#31 🔧 chore: CI 환경 대응을 위한 husky 조건부 실행 및 Node 18 환경 설정
  .nvmrc
  package.json
  pnpm-lock.yaml
  scripts/setup-git-hooks.cjs
Labels: ⚙ Setting

#41 ✨ feat: 메인, 계정설정 페이지 레이아웃 구성 및 적용
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/(auth)/user-setting/layout.tsx
  src/app/(board)/boards/[id]/edit/layout.tsx
  src/app/(board)/boards/[id]/layout.tsx
  src/app/(board)/boards/layout.tsx
  src/app/(board)/boards/new/layout.tsx
  src/app/(tasklist)/tasklists/layout.tsx
  src/app/(tasklist)/tasklists/page.tsx
  src/app/dashboard/layout.tsx
  src/app/myhistory/layout.tsx
  src/layouts/MainLayout.tsx
  src/layouts/SettingLayout.tsx
Labels: ✨ Feature, 🎨 Style

#22 ✨ feat: 공통 Modal 컴포넌트 구현
  eslint.config.mjs
  package-lock.json
  src/app/(tasklist)/modaltest/page.tsx
  src/app/(tasklist)/tasklist/page.tsx
  src/components/common/Modal/DeleteAccountModal.tsx
  src/components/common/Modal/InviteModal.tsx
  src/components/common/Modal/LogoutModal.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/PasswordChangeModal.tsx
  src/components/common/Modal/PasswordResetModal.tsx
  src/components/common/Modal/ProfileModal.tsx
  src/components/common/Modal/TodoCreateModal.tsx
  src/components/common/Modal/TodoModal.tsx
  src/stores/modalStore.ts
  tailwind.config.ts
Labels: ✨ Feature

#42 ✨ feat: Header 및 Sidebar 구현
  public/icons/icon-check.svg
  public/icons/icon-kebab.svg
  src/app/(board)/boards/page.tsx
  src/app/layout.tsx
  src/components/common/Dropdown/Item.tsx
  src/components/common/Dropdown/Menu.tsx
  src/layouts/Header/Header.tsx
  src/layouts/Header/Sidebar.tsx
  src/layouts/Header/TeamDropdown.tsx
  src/layouts/Header/UserDropdown.tsx
Labels: ✨ Feature
